# Generated by Django 5.2.7 on 2025-10-25 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_a', models.CharField(max_length=100)),
                ('time_b', models.CharField(max_length=100)),
                ('odd_time_a', models.DecimalField(decimal_places=2, max_digits=5)),
                ('odd_time_b', models.DecimalField(decimal_places=2, max_digits=5)),
                ('odd_empate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_jogo', models.DateTimeField()),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto para apostas'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=20)),
                ('resultado', models.CharField(blank=True, choices=[('TIME_A', 'Vitória Time A'), ('TIME_B', 'Vitória Time B'), ('EMPATE', 'Empate')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_apostado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('escolha', models.CharField(choices=[('TIME_A', 'Vitória Time A'), ('TIME_B', 'Vitória Time B'), ('EMPATE', 'Empate')], max_length=20)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('GANHA', 'Ganha'), ('PERDIDA', 'Perdida')], default='PENDENTE', max_length=20)),
                ('data_aposta', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apostas', to=settings.AUTH_USER_MODEL)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apostas', to='apostas.jogo')),
            ],
        ),
    ]
